services:
  mysql:
    container_name: 'mysql-container'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=van_go_db'
      - 'MYSQL_PASSWORD=vanGoPassword'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=vanGoUser'
    ports:
      - '3306:3306'
    volumes:	
    - ./data:/var/lib/mysql
